Adding a directory check and a /dev/null.

diff --git a/.dragonshark/games b/.dragonshark/games
--- a/.dragonshark/games
+++ b/.dragonshark/games
@@ -34,7 +34,7 @@ function dragonshark-games-set-roms-dir() {
         return 1
     fi
 
-    dragonshark-games-enumerate-external-device-dirs | grep "$DEV_DIR" > /dev/null
+    dragonshark-games-enumerate-external-device-dirs | grep "$DEV_DIR" > /dev/null 2> /dev/null
     if [[ ! $? ]]
     then
         echo "The given roms dir is not an external media directory" 1>&2
@@ -58,7 +58,13 @@ function dragonshark-games-get-roms-dir() {
 
 # Makes a backup of the save states.
 function dragonshark-games-saves-backup() {
-    rm "$1/backup.zip"
+    if [[ ! -d "$1" ]]
+    then
+        echo "Invalid backup directory: $1" 1>&2
+        return 2
+    fi
+
+    rm "$1/backup.zip" > /dev/null 2> /dev/null
     cd /mnt/SAVES && zip -r "$1/backup.zip" ./*
     return $?
 }
